[package]
name = "doppelganger-wrapper"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "doppelganger"
path = "src/doppelganger.rs"

[[bin]]
name = "doppelganger-parachain"
path = "src/doppelganger_parachain.rs"

[dependencies]
polkadot-sdk = {path = "/Users/pepo/parity/polkadot-sdk/umbrella", features = ["node", "serde", "doppelganger"] }
color-eyre = { version = "0.6.3", default-features = false }
