name: Cargo Build & Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
  workflow_call:

# cancel previous runs
concurrency:
    group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
    cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-Dwarnings"
  SKIP_WASM_BUILD: 1

jobs:
  ci:
    name: CI
    runs-on: parity-default
    timeout-minutes: 120

    steps:
      # https://github.com/jlumbroso/free-disk-space
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: false

      - name: Checkout
        uses: actions/checkout@v4
        with:
            fetch-depth: 0

      - name: Set rust version via common env file
        run: cat .github/env >> $GITHUB_ENV

      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          components: "clippy"
          toolchain: "${{env.RUST_STABLE_VERSION}}"

      - name: Fetch cache
        uses: Swatinem/rust-cache@f0deed1e0edfc6a9be95417288c0e1099b1eeec3 # v2.7.7
        with:
          shared-key: "tracker-cache"
          save-if: ${{ github.ref == 'refs/heads/main' }}

      - name: Install_deps
        run: |
          sudo apt update
          sudo apt install -y \
            protobuf-compiler \
            libssl-dev make cmake \
            build-essential clang \
            ca-certificates jq

      - name: rustup
        run: |
          rustup component add rust-src --toolchain 1.88.0-x86_64-unknown-linux-gnu
          rustup target add wasm32-unknown-unknown

      # - name: Clippy
      #   run: cargo clippy --all-targets --all-features

      - name: Build
        run:  cargo build

      - name: Tests
        run: cargo test
